apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas:
  selector:
    matchLabels:
      app: second-app
    #      tier: backend
  #    matchExpressions:
  #      - { key: app, operator: In, values: [ first-app, second-app ] }
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      containers:
        - name: second-node
          image: serhiimyronets/kub-first-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 5